### ISSUE TITLE
Hi, guys! Could you give me the URL about the book "Fundamental of Point cloud processing"? thks!

### ISSUE THREAD

**Issue by zhuyuanxiang** [Xin546946/point_cloud_processing#1]

**Comment by Xin546946** [comment]
Hi there,

Thanks for your interest. 

Unfortunately, there is no such book but an online lecture held by Dr. Jiaxin Li in Shenlanxueyuan. For further interest, you can visit the website: 
https://www.shenlanxueyuan.com/course/432

Best regards
Xin

**Comment by zhuyuanxiang** [comment]
I got. Thks!
